# Generated by Django 5.2.3 on 2025-06-15 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('baker', 'Baker'), ('cleaner', 'Cleaner'), ('accountant', 'Accountant'), ('storekeeper', 'Storekeeper'), ('developer', 'Developer')], default='staff', max_length=20)),
                ('staff_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
