# Generated by Django 5.2.3 on 2025-06-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrollprofile_hourly_rate_payrolladjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprofile',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set a fixed monthly salary. If > 0, this will override hourly rate calculations.', max_digits=10),
        ),
    ]
